### ISSUE TITLE
DL with a list in the DD, followed by another DL, doesn't work

### ISSUE THREAD

**Issue by samwilson** [samwilson/dokuwiki-plugin-definitionlist#2]
This should be fine, but it's breaking things:

```
  ; Term
  : Some parts:
  * Part 1
  * Part 2

  ; Another term : Definition
```

The second list can be either that sort-form or the normal mutli-line form. That line in-between is just empty (although should be allowed to be just-whitespace, I think). The output is this:

```
<dl class="plugin_definitionlist">
<dt><span class='term'>Term</span></dt>
<dd>Some parts:<ul>
<li class="level1"><div class="li"> Part 1</div>
</li>
<li class="level1"><div class="li"> Part 2</div>
</li>
</ul>

<p>
</dd>
<dt><span class='term'>Another term</span></dt>
<dd>Definition
</p>
```

I realise that this list-in-a-definition isn't exactly standard DokuWiki, but it at least shouldn't output invalid HTML.

**Comment by samwilson** [comment]
@ssahara do you have any ideas about this?

**Comment by samwilson** [comment]
(I meant to ping you too, @Chris--S. :-) )

I am wondering if one solution mightn't be to only allow a DD to continue to the next line only if the next line doesn't begin with whitespace (i.e. is a list or preformatted block). Then, at least if someone tried the above, it wouldn't look any good.

**Comment by Chris--S** [comment]
Hi,

No issue at all with you putting it on github.  Or redoing the plugin page to use your github repo for the main download link.

I'm taking a look to see what is causing the <p> open between the closing </ul> and the closing </dd>.

Most of the complex syntaxes within DokuWiki, like lists, are handled by call rewriters.  At the time I wrote the definition list plugin, there wasn't any facility for plugins to do something similar.  Now plugins can make use of the in-built 'nest' call rewriter.

I'm also wondering if the exit pattern for syntax modes like lists should be a look-ahead to a new line rather than (capturing) the new line itself.  That would allow both the list and the definition list to be ended by the same new line.  I tried a quick change to the list exit pattern, but it didn't work as expected.  I'm also trying to figure out why not.
- Chris

**Comment by samwilson** [comment]
Great! Thanks.

I haven't investigated the call rewriting facility. Will do so now.

I've been trialing a lookahead for the exit patter, making it `\n(?=[ \t]*\n)` and this works for all the normal situations but doesn't help with ordered lists in the DD.

I've added a few tests for these situations. The last three are failing.

**Comment by ssahara** [comment]
Hello, 
I am rather web-designer and have not enough knowledge php code. As a user of the definition plugin, I have never thought to use ul or ol html tag. I prefer approach to specify relevant class to dd element such dd.definition and dd.example for dt.term in css file. dd.example will be rendered as if  it is unordered list. IMO, using ul in dd element may be less-semantic html.

When I write more complex glossary page, I am usng exttab2 plugin which support MediaWiki style tables. It support nested table, so the approach used in exttab2 to convert wiki source to html might be working example for p tag issue in dd of definition plugin. I might wrongly understand something.

Satoshi Sahara

**Comment by samwilson** [comment]
@ssahara I think you're right, a UL in a DD is counter-semantic. If there's more than one item, it's better to put them in as separate DDs (which this plugin handles correctly). So disabling these wouldn't affect your usage of the plugin? (Oh, and this is using the asterisk syntax, rather than full HTML, but the theory's the same.)

It's interesting to [read](http://wiki.wikicreole.org/Creole%202.0/1.0%20additions%20in%202.0/Definition%20lists) that the Wiki Creole project, which attempts to find common ground between wiki markups, doesn't support definition lists at all, basically saying that they're not necessary!

**Comment by ssahara** [comment]
@samwilson After checking how my wiki users use definition plugin syntax, they use only inline cosmetics such **bold** or _italic_. So far, disabling block elements in a DD will not be issue. I will keep watching how the plugin will developed in future. I still continue developing my fork version of the plugin after previous push request to allow more flexible css styling. 

I am interested in definition plugin or DL-DT-DD tags for extending my own usage without adverse effects to general Wiki syntax, because these tags are not officially supported in Wiki. :-)

**Comment by Chris--S** [comment]
1. Semantics:  lists within definition lists are fine, in fact w3c gives an example of one in its discussion of lists, see http://www.w3.org/TR/html401/struct/lists.html#h-10.1 (the second recipe, just above section 10.2 title).
2. The problem:  Its an issue with the DokuWiki parser.  On exiting a 'block' syntax mode (the list) DokuWiki opens a paragraph without realising its still within a another 'block' syntax mode (the definition list).  I'm not sure if its an easy problem to solve - but the solution, if feasible, lies within DokuWiki rather than with this plugin.

**Comment by Chris--S** [comment]
I was hasty.  Solution is within scope of the plugin.  Will push something in the next day or two, once I update ODT code as well.

**Comment by samwilson** [comment]
Great! Thanks for looking at this. :-)

**Comment by Chris--S** [comment]
See PR#3

**Comment by samwilson** [comment]
Oops, this is all sorted. Closing now. :-)
